# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build: ./server/
    # command: ./wait-for-postgres.sh db ./api-example
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=example
      - APP_PORT=5000
      - PG_HOST=db
      - PG_PORT=5432
      - LOG_LEVEL=debug
      - PG_MIGRATIONS_PATH=file://./migrations
      - PG_PAS=example
      - PG_SSLMODE=disable
      - PG_USERNAME=postgres
      - PG_DBNAME=postgres
      - ENV=production
      - JWT_SECRET=scrtstring #TODO ?
      - MONGO_URI=mongodb://root:example@localhost:8092/?authSource=admin
  db:
    image: postgres:latest
    restart: always
    # volumes:
    # - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  mongo:
    image: mongo
    restart: always
    ports:
      - 8092:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example