# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class KeepStub(object):
    """protoc -I=./api/keep --python_out=./googlekeep ./api/keep/service.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWords = channel.unary_unary(
                '/Keep/GetWords',
                request_serializer=service__pb2.SearchRequest.SerializeToString,
                response_deserializer=service__pb2.SearchResult.FromString,
                )


class KeepServicer(object):
    """protoc -I=./api/keep --python_out=./googlekeep ./api/keep/service.proto

    """

    def GetWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeepServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWords,
                    request_deserializer=service__pb2.SearchRequest.FromString,
                    response_serializer=service__pb2.SearchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Keep', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Keep(object):
    """protoc -I=./api/keep --python_out=./googlekeep ./api/keep/service.proto

    """

    @staticmethod
    def GetWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Keep/GetWords',
            service__pb2.SearchRequest.SerializeToString,
            service__pb2.SearchResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
